### ISSUE TITLE
Bark通知跳到叮咚之后叮咚提示版本过低

### ISSUE THREAD

**Issue by trombonist852** [wu491925129/script#3]
如题，请教下大佬这个改怎么解决？

**Comment by wu491925129** [comment]
不影响，直接返回就行了。这是因为叮咚买菜没有开放购物车的URL scheme，我这边用的是ddxq://，对于没有开放的他都是跳转版本过低页面

**Comment by trombonist852** [comment]
重启了一遍好了

**Comment by trombonist852** [comment]
> 不影响，直接返回就行了。这是因为叮咚买菜没有开放购物车的URL scheme，我这边用的是ddxq://，对于没有开放的他都是跳转版本过低页面

好滴，感谢大佬！上海抢菜太难了现在，唉
